GET http://localhost:8080/health

###
POST http://localhost:8080/customers
Content-Type: application/json

{
  "firstName": "hg",
  "lastName": "lastname",
  "email": "email@dk.com",
  "address": "address",
  "phone": "1234567890"
}

###

GET http://localhost:8080/customers
Authorization: Basic email@dk.com mypass

###

PATCH http://localhost:8080/customers/cb4bce56-4b27-4f53-95a7-a44dbb269f0c
Content-Type: application/json

{
  "phone": "123455666677"
}

###

GET http://localhost:8080/customers/cb4bce56-4b27-4f53-95a7-a44dbb269f0c

###
DELETE http://localhost:8080/customers/cb4bce56-4b27-4f53-95a7-a44dbb269f0c

###
POST http://localhost:8080/customer-accounts
Authorization: Basic email@dk.com mypass
Content-Type: application/json

{
  "balance": "100",
  "currency": "EURO"
}

###
GET http://localhost:8080/customer-accounts
Authorization: Basic email@dk.com mypass
###

GET http://localhost:8080/customer-accounts/123

###
PATCH http://localhost:8080/customer-accounts/123
Content-Type: application/json

{
  "balance": "200",
  "currency": "UAH"
}

###
DELETE http://localhost:8080/customer-accounts/123
###
POST http://localhost:8080/transactions
Authorization: Basic email@dk.com mypass
Content-Type: application/json

{
  "debitId": "debit1",
  "creditId": "credit1",
  "amount": "100",
  "description": "money"
}

###
GET http://localhost:8080/transactions

###
GET http://localhost:8080/transactions/d769db8a-af10-4724-b1bc-9e91fd9344e0

###
POST http://localhost:8080/managers
Content-Type: application/json

{
  "firstName": "Hough",
  "lastName": "Lori",
  "email": "email@dk.com",
  "password": "mypass"
}

###
GET http://localhost:8080/managers

###

GET http://localhost:8080/managers/009052ad-f373-4c62-baa8-2c088855f544

###
PATCH http://localhost:8080/managers/009052ad-f373-4c62-baa8-2c088855f544
Content-Type: application/json

{
  "firstName": "Fray",
  "email": "f.max@ok.ok",
  "password": "notmypass"
}

###
DELETE http://localhost:8080/managers/009052ad-f373-4c62-baa8-2c088855f544