GET http://localhost:8080/health
###
POST http://localhost:8080/customers
Content-Type: application/json

{"firstName": "firstname",
"lastName": "lastname",
"email": "email",
"address": "address",
"phone": "phone"}
###

GET http://localhost:8080/customers
###

PATCH http://localhost:8080/customers/123
Content-Type: application/json

{
  "lastName": "lastname",
  "email": "email",
  "address": "address",
  "phone": "phone"}
###

GET http://localhost:8080/customers/123

###
DELETE http://localhost:8080/customers/123
###
POST http://localhost:8080/customer-accounts
Content-Type: application/json

{"balance": "100",
  "currency": "EURO"}

